spring:
    data:
        mongodb:
            uri: mongodb+srv://alpapie0908:gTFIxjWtsHtJgIRo@cluster0.yuzob.mongodb.net/?retryWrites=true&w=majority
            database: letsPlay
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: alpapie1998 #${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
  port: 8443